import assert from 'node:assert/strict';
import { test } from 'node:test';
let mod; try {mod=await import('../../infra/cloudflare/media-gateway.mjs');}catch{}
const get=()=>{assert.ok(mod,'Private media gateway not implemented');return mod;};
test('missing Access cannot serve media',async()=>{const m=get();assert.equal((await m.default.fetch(new Request('https://test/media/S02E01/original'),{},{})).status,403)});
test('wrong identity cannot serve media',async()=>{const m=get();assert.equal((await m.default.fetch(new Request('https://test/media/S02E01/original'),{}, {access:{aud:m.AUD,getIdentity:async()=>({email:'other@example.com'})}})).status,403)});
test('blocked final three cannot select an object',()=>{const m=get();for(const id of ['S02E15','S02E16','S02E17'])assert.equal(m.sourceFor(id,'original'),null)});
test('invalid identifiers do not select an object',()=>{const m=get();for(const id of ['../S02E01','S01E01','S02E18','tmdb:1018'])assert.equal(m.sourceFor(id,'original'),null)});
test('primary season promo is correctly identified',()=>{const m=get();assert.equal(m.sourceFor('S02_CLIP03','original').bytes,7945453)});
test('valid closed and suffix range',()=>{const m=get();assert.deepEqual(m.parseRange('bytes=0-31',100),{offset:0,length:32});assert.deepEqual(m.parseRange('bytes=-10',100),{offset:90,length:10})});
test('malformed multiple and unsatisfied ranges rejected',()=>{const m=get();for(const s of ['bytes=0-1,5-6','bytes=100-','bytes=3-1','bytes=-0','bytes=a-b'])assert.throws(()=>m.parseRange(s,100))});
test('oversized end clamps to exact available length',()=>{const m=get();assert.deepEqual(m.parseRange('bytes=90-999',100),{offset:90,length:10})});

const ownerContext=()=>({access:{aud:mod.AUD,getIdentity:async()=>({email:'cinewatchtv.stream@gmail.com'})}});
function bucketFor(item){return {head:async key=>key===item.key?{size:item.bytes,customMetadata:{sha256:item.sha256}}:null,get:async(key,options)=>({body:new Uint8Array(options?.range?.length??32).fill(7)})};}
test('owner receives exact partial-content headers and bytes',async()=>{const m=get(),item=m.sourceFor('S02_CLIP03','original');const response=await m.default.fetch(new Request('https://test/media/S02_CLIP03/original',{headers:{Range:'bytes=8-23'}}),{MEDIA:bucketFor(item)},ownerContext());assert.equal(response.status,206);assert.equal(response.headers.get('Content-Range'),`bytes 8-23/${item.bytes}`);assert.equal(response.headers.get('Content-Length'),'16');assert.equal((await response.arrayBuffer()).byteLength,16);assert.match(response.headers.get('Cache-Control'),/no-store/)});
test('owner HEAD verifies source without fetching body',async()=>{const m=get(),item=m.sourceFor('S02_CLIP03','original');let fetched=false;const bucket=bucketFor(item);bucket.get=async()=>{fetched=true;throw Error('HEAD must not fetch')};const response=await m.default.fetch(new Request('https://test/media/S02_CLIP03/original',{method:'HEAD'}),{MEDIA:bucket},ownerContext());assert.equal(response.status,200);assert.equal(response.headers.get('Content-Length'),String(item.bytes));assert.equal(fetched,false)});
test('mismatched storage hash fails closed',async()=>{const m=get(),item=m.sourceFor('S02_CLIP03','original');const bucket=bucketFor(item);bucket.head=async()=>({size:item.bytes,customMetadata:{sha256:'bad'}});assert.equal((await m.default.fetch(new Request('https://test/media/S02_CLIP03/original'),{MEDIA:bucket},ownerContext())).status,503)});
test('unsatisfied owner range returns 416 without fetching',async()=>{const m=get(),item=m.sourceFor('S02_CLIP03','original');const response=await m.default.fetch(new Request('https://test/media/S02_CLIP03/original',{headers:{Range:`bytes=${item.bytes}-`}}),{MEDIA:bucketFor(item)},ownerContext());assert.equal(response.status,416);assert.equal(response.headers.get('Content-Range'),`bytes */${item.bytes}`)});
test('forbidden episode stays denied even with authenticated owner',async()=>{const m=get();assert.equal((await m.default.fetch(new Request('https://test/media/S02E15/original'),{MEDIA:{}},ownerContext())).status,403)});
test('derived quality requires matching parent, height, hash and immutable key',()=>{const m=get(),original=m.sourceFor('S02_CLIP03','original'),sha='a'.repeat(64);const valid={parent_sha256:original.sha256,height:240,bytes:10,sha256:sha,key:`simulated-rights/bonanza/derived/S02_CLIP03/240p/${sha}.mp4`};assert.deepEqual(m.sourceFor('S02_CLIP03','240p',{S02_CLIP03:valid}),valid);for(const patch of [{parent_sha256:'bad'},{height:480},{bytes:0},{sha256:'bad'},{key:'other.mp4'}])assert.equal(m.sourceFor('S02_CLIP03','240p',{S02_CLIP03:{...valid,...patch}}),null)});
test('native owner identity response is fixed and never exposes the assertion',async()=>{const m=get();const response=await m.default.fetch(new Request('https://test/identity'),{},ownerContext());assert.equal(response.status,200);assert.deepEqual(await response.json(),{email:'cinewatchtv.stream@gmail.com',authorized:true});assert.match(response.headers.get('Cache-Control'),/no-store/)});
test('authorize cannot redirect without exact nonce and assertion',async()=>{const m=get();for(const url of ['https://test/authorize','https://test/authorize?state=bad'])assert.equal((await m.default.fetch(new Request(url),{},ownerContext())).status,400)});
test('native owner assertion is passed only in a nonce-bound fragment',async()=>{const m=get(),nonce='a'.repeat(64),jwt='e30.e30.ZmFrZQ';for(const headers of [{'Cf-Access-Jwt-Assertion':jwt},{Cookie:`CF_Authorization=${jwt}`}]){const response=await m.default.fetch(new Request(`https://test/authorize?state=${nonce}`,{headers}),{},ownerContext());assert.equal(response.status,303);const url=new URL(response.headers.get('Location'));assert.equal(url.origin,'https://www.cinewatchtv.com');assert.equal(url.search,'');assert.equal(new URLSearchParams(url.hash.slice(1)).get('state'),nonce);assert.equal(new URLSearchParams(url.hash.slice(1)).get('token'),jwt)}});
